name: snowflake_sandbox
version: "1.0.0"
profile: snowflake_sandbox

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  snowflake_sandbox:
    staging:
      +schema: staging
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
      +transient: false
    presentation:
      +schema: presentation
      +materialized: view

seeds:
  snowflake_sandbox:
    +schema: staging
    magnitude_types:
      +column_types:
        MAGNITUDE_TYPE_CODE: varchar(20)
        MAGNITUDE_TYPE_DESC: varchar(100)

