USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE NETWORK RULE DWH_DEV.RAW.USGS_EARTHQUAKE_NETWORK_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('earthquake.usgs.gov');

CREATE OR REPLACE NETWORK RULE DWH_TEST.RAW.USGS_EARTHQUAKE_NETWORK_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('earthquake.usgs.gov');

CREATE OR REPLACE NETWORK RULE DWH_PROD.RAW.USGS_EARTHQUAKE_NETWORK_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('earthquake.usgs.gov');

